name: Python application test with GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb tk
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run xvfb
      run: |
        Xvfb :99 &
        export DISPLAY=:99

    - name: Run tests
      run: |
        target_genie_crispr_GUI
